Repository ahmedelazab1220/online_exam_app, pull requests merged in 2025-03, with the labels that each got.

#25 [TEST] | Add email validation tests for ForgetPasswordCubit
  pubspec.lock
  pubspec.yaml
  test/features/forget_password/forget_password_cubit_test.dart
  test/features/forget_password/forget_password_cubit_test.mocks.dart
  test/widget_test.dart
Labels: refactor, testing

#28 [FEATURE] | Add OTP verification ui feature.
  assets/svgs/error_icon.svg
  devtools_options.yaml
  lib/core/assets/app_icons.dart
  lib/core/navigation/routes.dart
  lib/features/forget_password/presentation/view/forget_password_view.dart
  lib/features/otp_verify/presentation/view/otp_verify_view.dart
  lib/features/otp_verify/presentation/view/widgets/otp_form.dart
  lib/features/otp_verify/presentation/view/widgets/otp_verify_form.dart
Labels: enhancement

#32 [FEATURE] | Add reset password feature with localization support
  android/app/.cxx/Debug/5m4g44s1/arm64-v8a/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/armeabi-v7a/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/x86/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/x86_64/configure_fingerprint.bin
  assets/translations/ar.json
  assets/translations/en.json
  lib/core/navigation/routes.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/features/otp_verify/presentation/view/otp_verify_view.dart
  lib/features/reset_password/presentation/view/reset_password_view.dart
  lib/features/reset_password/presentation/view/widgets/reset_password_form.dart
Labels: enhancement

#26 [FEATURE] | Add bottom navigation bar.
  assets/svgs/selected_explore_icon.svg
  assets/svgs/selected_profile_icon.svg
  assets/svgs/unselected_result_icon.svg
  assets/translations/ar.json
  assets/translations/en.json
  lib/core/assets/app_icons.dart
  lib/core/di/di.config.dart
  lib/core/navigation/routes.dart
  lib/core/theme/app_theme.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/features/bottom_navigation_bar/presentation/view/bottom_navigation_bar_view.dart
  lib/features/bottom_navigation_bar/presentation/view_model/bottom_nav_bar_cubit/bottom_nav_bar_cubit.dart
  lib/features/bottom_navigation_bar/presentation/view_model/bottom_nav_bar_cubit/bottom_nav_bar_state.dart
  lib/features/explore/presentation/view/explore_view.dart
  lib/features/profile/presentation/view/profile_view.dart
  lib/features/result/presentation/view/result_view.dart
  lib/main.dart
Labels: enhancement

#33 [FEATURE] | Add reset password feature with secure storage integration
  android/app/.cxx/Debug/5m4g44s1/arm64-v8a/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/armeabi-v7a/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/x86/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/x86_64/configure_fingerprint.bin
  lib/core/di/di.config.dart
  lib/core/utils/flutter_secure_storage_module.dart
  lib/core/utils/validation/validator.dart
  lib/data/api/auth/auth_retrofit_client.dart
  lib/data/api/auth/auth_retrofit_client.g.dart
  lib/data/api/models/auth/reset_password/request/reset_password_request_dto.dart
  lib/data/api/models/auth/reset_password/request/reset_password_request_dto.g.dart
  lib/data/api/models/auth/reset_password/response/reset_password_response_dto.dart
  lib/data/api/models/auth/reset_password/response/reset_password_response_dto.g.dart
  lib/data/datasource/contract/auth_local_datasource.dart
  lib/data/datasource/contract/auth_remote_datasource.dart
  lib/data/datasource/local/auth_local_datasource_impl.dart
  lib/data/datasource/remote/auth_remote_datasource_impl.dart
  lib/data/repositories/auth_repository_impl.dart
  lib/domain/entities/reset_password_entity.dart
  lib/domain/repositories/auth_repository.dart
  lib/domain/use_cases/reset_password_use_case.dart
  lib/features/reset_password/presentation/view/reset_password_view.dart
  lib/features/reset_password/presentation/view/widgets/reset_password_form.dart
  lib/features/reset_password/presentation/view_model/reset_password_cubit/reset_password_cubit.dart
  lib/features/reset_password/presentation/view_model/reset_password_cubit/reset_password_state.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  test/features/forget_password/forget_password_cubit_test.mocks.dart
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: enhancement

#35 [FEATURE] | Implement signup feature with Hive storage, BLoC, API integration, MVI Pattern, Clean architecture.
  android/app/.cxx/Debug/5m4g44s1/arm64-v8a/.cmake/api/v1/reply/index-2025-03-10T01-01-46-0316.json
  android/app/.cxx/Debug/5m4g44s1/arm64-v8a/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/armeabi-v7a/.cmake/api/v1/reply/index-2025-03-10T01-01-48-0588.json
  android/app/.cxx/Debug/5m4g44s1/armeabi-v7a/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/x86/.cmake/api/v1/reply/index-2025-03-10T01-01-50-0700.json
  android/app/.cxx/Debug/5m4g44s1/x86/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/x86_64/.cmake/api/v1/reply/index-2025-03-10T01-01-52-0279.json
  android/app/.cxx/Debug/5m4g44s1/x86_64/configure_fingerprint.bin
  assets/translations/ar.json
  assets/translations/en.json
  lib/core/base/base_state.dart
  lib/core/di/di.config.dart
  lib/core/utils/bloc_observer/bloc_observer_service.dart
  lib/core/utils/constants.dart
  lib/core/utils/hive_storage_module.dart
  lib/core/utils/l10n/locale_keys.g.dart
  lib/core/utils/validation/validator.dart
  lib/data/api/auth/auth_retrofit_client.dart
  lib/data/api/auth/auth_retrofit_client.g.dart
  lib/data/api/models/auth/signup/request/signup_request_dto.dart
  lib/data/api/models/auth/signup/request/signup_request_dto.g.dart
  lib/data/api/models/auth/signup/response/signup_response_dto.dart
  lib/data/api/models/auth/signup/response/signup_response_dto.g.dart
  lib/data/api/models/auth/user/user_dto.dart
  lib/data/api/models/auth/user/user_dto.g.dart
  lib/data/datasource/contract/auth_local_datasource.dart
  lib/data/datasource/contract/auth_remote_datasource.dart
  lib/data/datasource/local/auth_local_datasource_impl.dart
  lib/data/datasource/remote/auth_remote_datasource_impl.dart
  lib/data/local_database/models/user/local_user.dart
  lib/data/local_database/models/user/local_user.g.dart
  lib/data/local_database/user_local_database/user_local_database.dart
  lib/data/repositories/auth_repository_impl.dart
  lib/domain/entities/signup_user_entity.dart
  lib/domain/entities/user_entity.dart
  lib/domain/repositories/auth_repository.dart
  lib/domain/use_cases/signup_use_case.dart
  lib/features/auth/sign_up/presentation/view/sign_up_view.dart
  lib/features/auth/sign_up/presentation/view/widgets/already_have_account_sign_up.dart
  lib/features/auth/sign_up/presentation/view/widgets/sign_up_form.dart
  lib/features/auth/sign_up/presentation/view_model/signup_cubit/signup_cubit.dart
  lib/features/auth/sign_up/presentation/view_model/signup_cubit/signup_state.dart
  lib/features/forget_password/presentation/view/widgets/forget_password_form.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  test/features/forget_password/forget_password_cubit_test.dart
  test/features/forget_password/forget_password_cubit_test.mocks.dart
Labels: enhancement

#37 [FIX] | Register LocalUserAdapter, adjust dependency configuration and optimize hive to improve performance.
  android/app/.cxx/Debug/5m4g44s1/arm64-v8a/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/armeabi-v7a/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/x86/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/x86_64/configure_fingerprint.bin
  lib/core/utils/hive_storage_module.dart
  lib/data/repositories/auth_repository_impl.dart
  lib/main.dart
Labels: refactor

#38 [FEATURE] | Implement login feature with Hive storage, BLoC, API integration, MVI Pattern, Clean architecture.
  analysis_options.yaml
  android/app/.cxx/Debug/5m4g44s1/arm64-v8a/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/armeabi-v7a/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/x86/configure_fingerprint.bin
  android/app/.cxx/Debug/5m4g44s1/x86_64/configure_fingerprint.bin
  lib/core/assets/app_colors.dart
  lib/core/di/di.config.dart
  lib/data/api/auth/auth_retrofit_client.dart
  lib/data/api/auth/auth_retrofit_client.g.dart
  lib/data/api/models/auth/forget_password/response/forget_password_response_dto.dart
  lib/data/api/models/auth/login/request/login_user_request_dto.dart
  lib/data/api/models/auth/login/request/login_user_request_dto.g.dart
  lib/data/api/models/auth/login/response/login_user_response_dto.dart
  lib/data/api/models/auth/login/response/login_user_response_dto.g.dart
  lib/data/api/models/auth/reset_password/response/reset_password_response_dto.dart
  lib/data/api/models/auth/signup/request/signup_request_dto.dart
  lib/data/api/models/auth/user/user_dto.dart
  lib/data/datasource/contract/auth_local_datasource.dart
  lib/data/datasource/contract/auth_remote_datasource.dart
  lib/data/datasource/local/auth_local_datasource_impl.dart
  lib/data/datasource/remote/auth_remote_datasource_impl.dart
  lib/data/local_database/models/user/local_user.dart
  lib/data/repositories/auth_repository_impl.dart
  lib/domain/entities/auth/authentication_response.dart
  lib/domain/entities/auth/forget_password_entity.dart
  lib/domain/entities/auth/login_user_entity.dart
  lib/domain/entities/auth/reset_password_entity.dart
  lib/domain/entities/auth/signup_user_entity.dart
  lib/domain/entities/auth/user_entity.dart
  lib/domain/repositories/auth_repository.dart
  lib/domain/use_cases/forget_password_use_case.dart
  lib/domain/use_cases/login_use_case.dart
  lib/domain/use_cases/reset_password_use_case.dart
  lib/domain/use_cases/signup_use_case.dart
  lib/features/auth/login/presentation/view/login_view.dart
  lib/features/auth/login/presentation/view/widgets/do_not_have_an_account_widget.dart
  lib/features/auth/login/presentation/view/widgets/login_form.dart
  lib/features/auth/login/presentation/view/widgets/remember_me_and_forget_password_widget.dart
  lib/features/auth/login/presentation/view_model/login_cubit/login_cubit.dart
  lib/features/auth/login/presentation/view_model/login_cubit/login_state.dart
  lib/features/auth/sign_up/presentation/view_model/signup_cubit/signup_cubit.dart
  lib/features/forget_password/presentation/view_model/forget_password_cubit/forget_password_cubit.dart
  lib/features/otp_verify/presentation/view_model/otp_verify_cubit/otp_verify_cubit.dart
  lib/features/reset_password/presentation/view_model/reset_password_cubit/reset_password_cubit.dart
  test/features/forget_password/forget_password_cubit_test.mocks.dart
Labels: enhancement
